spring:
  datasource:
    url: jdbc:mysql://192.168.92.172:3306/mnsx_spring?characterEncoding=utf8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123123

